"""add ngo and claims models

Revision ID: 7f15629f5272
Revises: c58ade28ca49
Create Date: 2026-05-27 18:56:07.252673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f15629f5272'
down_revision: Union[str, Sequence[str], None] = 'c58ade28ca49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_claims_id'), 'claims', ['id'], unique=False)
    op.alter_column('donations', 'quantity',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_column('donations', 'expiry')
    op.drop_column('donations', 'is_deleted')
    op.drop_column('donations', 'location')
    op.add_column('ngos', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('ngos', sa.Column('registration_number', sa.String(), nullable=True))
    op.add_column('ngos', sa.Column('focus_areas', sa.String(), nullable=True))
    op.add_column('ngos', sa.Column('capacity_per_day', sa.Integer(), nullable=True))
    op.add_column('ngos', sa.Column('latitude', sa.String(), nullable=True))
    op.add_column('ngos', sa.Column('longitude', sa.String(), nullable=True))
    op.create_index(op.f('ix_ngos_id'), 'ngos', ['id'], unique=False)
    op.create_foreign_key(None, 'ngos', 'users', ['user_id'], ['id'])
    op.drop_column('ngos', 'contact')
    op.drop_column('ngos', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ngos', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('ngos', sa.Column('contact', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ngos', type_='foreignkey')
    op.drop_index(op.f('ix_ngos_id'), table_name='ngos')
    op.drop_column('ngos', 'longitude')
    op.drop_column('ngos', 'latitude')
    op.drop_column('ngos', 'capacity_per_day')
    op.drop_column('ngos', 'focus_areas')
    op.drop_column('ngos', 'registration_number')
    op.drop_column('ngos', 'user_id')
    op.add_column('donations', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('donations', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('donations', sa.Column('expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.alter_column('donations', 'quantity',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_claims_id'), table_name='claims')
    op.drop_column('claims', 'confirmed_at')
    # ### end Alembic commands ###
